# Generated by Django 4.2.10 on 2024-03-20 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 6, 26, 38, 172647, tzinfo=datetime.timezone.utc)),
        ),
    ]
