# Generated by Django 4.2.10 on 2024-03-26 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 7, 53, 10, 713892, tzinfo=datetime.timezone.utc)),
        ),
    ]
