# Generated by Django 4.2.10 on 2024-03-27 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 6, 23, 36, 940652, tzinfo=datetime.timezone.utc)),
        ),
    ]
